---
- name: Add unit file for Puma
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: '/home/{{ deploy_user }}/db_config'
    owner: '{{ deploy_user }}'
    group: '{{ deploy_user }}'

- name: enable puma
  systemd: name=puma enabled=yes

#- name: Fetch the latest version of application code
#  git:
#    repo: 'https://github.com/express42/reddit.git'
#    dest: /home/{{ deploy_user }}/reddit
#    version: monolith
#  notify: reload puma
#- name: Bundle install
#  bundler:
#    state: present
#    chdir: /home/{{ deploy_user }}/reddit
#  notify: reload puma
