---
- name: Provisioning App
  hosts: all
  become: true
#  vars:
#    db_host: 10.128.0.10
  tasks:
    - name: Update repositories cache and install "git, ruby full and required" package
      ansible.builtin.apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - git
        - ruby-full
        - ruby-bundler
        - build-essential
#    - name: Add unit file for Puma
#      copy:
#        src: files/puma.service
#        dest: /etc/systemd/system/puma.service
#      notify: reload puma
#    - name: Add config for DB connection
#      template:
#        src: templates/db_config.j2
##	dest: /home/appuser/db_config
##        owner: appuser
##        group: appuser
#        dest: /home/ubuntu/db_config
#        owner: ubuntu
#        group: ubuntu
#    - name: enable puma
#      systemd: name=puma enabled=yes
#    - name: Fetch the latest version of application code
#      git:
#        repo: 'https://github.com/express42/reddit.git'
##        dest: /home/appuser/reddit
#        dest: /home/ubuntu/reddit
#        version: monolith
#      notify: reload puma
#    - name: Bundle install
#      bundler:
#        state: present
###        chdir: /home/appuser/reddit
#        chdir: /home/ubuntu/reddit
#      notify: reload puma
#  handlers:
#    - name: reload puma
#      systemd: name=puma state=restarted
